#!/usr/bin/env python3
"""
AMP Marketing — Export Website Copy to PDF for Humanization
============================================================
Reads content_map.json (generated by export_for_humanization.py) and
produces a clean PDF with clear page/block markers that AISEO can process.

Splits into multiple PDFs if needed to avoid AISEO's character limits.

Output:
  - scripts/amp_marketing_copy_part1.pdf  (Pages 1-8)
  - scripts/amp_marketing_copy_part2.pdf  (Pages 9-15)

Usage: python scripts/export_pdf_for_humanization.py
"""

import json
import os
import sys

from fpdf import FPDF


# ── Block type labels ─────────────────────────────────────────────────────────
LABELS = {
    "meta": "SEO META",
    "jsx": "PAGE COPY",
    "data": "CONTENT BLOCK",
    "bullet": "BULLET POINT",
    "faq_q": "FAQ QUESTION",
    "faq_a": "FAQ ANSWER",
}


class CopyPDF(FPDF):
    """Custom PDF with headers/footers for the humanization export."""

    def __init__(self, part_num, total_parts):
        super().__init__()
        self.part_num = part_num
        self.total_parts = total_parts

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(
            0,
            8,
            f"AMP Marketing - Website Copy for Humanization (Part {self.part_num}/{self.total_parts})",
            align="C",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def add_instructions(self):
        """Add instruction block at the top of the PDF."""
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(0, 0, 0)
        self.cell(
            0,
            10,
            "AMP Marketing - Complete Website Copy",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.set_font("Helvetica", "", 11)
        self.cell(
            0, 7, "Export for Humanization via AISEO.ai", new_x="LMARGIN", new_y="NEXT"
        )
        self.ln(5)

        self.set_font("Helvetica", "B", 11)
        self.cell(0, 7, "INSTRUCTIONS:", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 10)
        instructions = [
            "- Each section is marked with ===PAGE=== headers showing page name and source file",
            "- Text blocks are numbered [BLOCK-XX] with type labels (CONTENT BLOCK, PAGE COPY, etc.)",
            "- When humanizing, KEEP all ===PAGE=== and [BLOCK-XX] markers exactly as they are",
            "- Only change the text BETWEEN the [BLOCK-XX] and [/BLOCK-XX] markers",
            "- Save the humanized version and we will map it back automatically",
            "- DO NOT remove, rename, or reorder any markers",
        ]
        for inst in instructions:
            self.cell(0, 6, inst, new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

        # Separator
        self.set_draw_color(0, 0, 0)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(8)

    def add_page_section(self, display_name, file_path, blocks):
        """Add a full page section with all its blocks."""
        # Page header bar
        self.set_fill_color(30, 41, 59)  # dark slate
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 12)
        self.cell(
            0,
            10,
            f"  ===PAGE: {display_name} ({file_path})===",
            fill=True,
            new_x="LMARGIN",
            new_y="NEXT",
        )

        # Source file reference
        self.set_text_color(120, 120, 120)
        self.set_font("Helvetica", "I", 9)
        self.cell(
            0,
            6,
            f"Source: {file_path}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.ln(3)

        for block in blocks:
            block_id = block["id"]
            btype = block["type"]
            text = block["original"]
            label = LABELS.get(btype, "TEXT")

            # Check if we need a new page (leave room for marker + content)
            if self.get_y() > 250:
                self.add_page()

            # Block start marker
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(79, 70, 229)  # indigo
            self.cell(
                0,
                6,
                f"[BLOCK-{block_id}] ({label})",
                new_x="LMARGIN",
                new_y="NEXT",
            )

            # Content text - clean encoding for PDF
            self.set_font("Helvetica", "", 10)
            self.set_text_color(30, 30, 30)
            clean_text = (
                text.replace("\u2019", "'")
                .replace("\u2018", "'")
                .replace("\u201c", '"')
                .replace("\u201d", '"')
                .replace("\u2014", "--")
                .replace("\u2013", "-")
                .replace("\u2026", "...")
                .replace("\u2022", "-")
                .replace("\u2705", "[check]")
                .replace("\u2713", "[check]")
                .replace("\u2716", "[x]")
                .replace("\u00a0", " ")
            )
            # Use multi_cell for word wrapping
            self.multi_cell(0, 5.5, clean_text, new_x="LMARGIN", new_y="NEXT")

            # Block end marker
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(79, 70, 229)
            self.cell(
                0,
                6,
                f"[/BLOCK-{block_id}]",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            self.ln(3)

        # End page marker
        if self.get_y() > 265:
            self.add_page()
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(30, 41, 59)
        self.cell(
            0,
            6,
            f"===END PAGE: {display_name}===",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.ln(6)


def build_pdfs():
    """Build PDF exports split into 2 parts to avoid AISEO truncation."""
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    json_path = "scripts/content_map.json"
    if not os.path.exists(json_path):
        print(f"ERROR: {json_path} not found. Run export_for_humanization.py first.")
        sys.exit(1)

    with open(json_path, "r", encoding="utf-8") as f:
        content_map = json.load(f)

    # Convert to ordered list
    pages = list(content_map.items())
    total_pages = len(pages)

    # Split roughly in half
    mid = (total_pages + 1) // 2
    parts = [
        pages[:mid],  # Part 1: ~8 pages
        pages[mid:],  # Part 2: ~7 pages
    ]
    total_parts = len(parts)

    total_blocks = 0
    total_words = 0
    output_files = []

    for part_idx, part_pages in enumerate(parts):
        part_num = part_idx + 1
        pdf = CopyPDF(part_num, total_parts)
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()
        pdf.add_instructions()

        part_blocks = 0
        part_words = 0

        for file_path, page_data in part_pages:
            display_name = page_data["display_name"]
            blocks = page_data["blocks"]

            pdf.add_page_section(display_name, file_path, blocks)

            block_count = len(blocks)
            word_count = sum(len(b["original"].split()) for b in blocks)
            part_blocks += block_count
            part_words += word_count
            print(
                f"  Part {part_num} | {display_name}: {block_count} blocks, {word_count} words"
            )

        # Summary page
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Summary - Part {part_num}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(
            0,
            7,
            f"Pages in this file: {len(part_pages)}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.cell(
            0,
            7,
            f"Total text blocks: {part_blocks}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.cell(
            0,
            7,
            f"Total words: ~{part_words:,}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "Pages included:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for fp, pd in part_pages:
            pdf.cell(
                0,
                6,
                f"  - {pd['display_name']} ({fp})",
                new_x="LMARGIN",
                new_y="NEXT",
            )

        out_path = f"scripts/amp_marketing_copy_part{part_num}.pdf"
        pdf.output(out_path)
        output_files.append(out_path)
        print(f"\n  PDF: {out_path} ({part_blocks} blocks, ~{part_words:,} words)")

        total_blocks += part_blocks
        total_words += part_words

    # Also generate a single combined PDF
    print("\n--- Generating combined single PDF ---")
    combined = CopyPDF(1, 1)
    combined.part_num = 1
    combined.total_parts = 1
    combined.set_auto_page_break(auto=True, margin=20)
    combined.add_page()
    combined.add_instructions()

    for file_path, page_data in pages:
        combined.add_page_section(file_path, file_path, page_data["blocks"])

    combined_path = "scripts/amp_marketing_full_copy.pdf"
    combined.output(combined_path)
    output_files.append(combined_path)
    print(f"  Combined PDF: {combined_path}")

    print(f"\n{'=' * 60}")
    print(
        f"DONE! {total_blocks} blocks, ~{total_words:,} words across {total_pages} pages"
    )
    print(f"{'=' * 60}")
    print(f"\nGenerated files:")
    for f in output_files:
        size_kb = os.path.getsize(f) / 1024
        print(f"  {f} ({size_kb:.0f} KB)")
    print(f"\nNext steps:")
    print(f"  1. Upload Part 1 to AISEO 'Make it Undetectable'")
    print(f"  2. Upload Part 2 to AISEO 'Make it Undetectable'")
    print(f"  3. Download both humanized versions")
    print(
        f"  4. Run: python scripts/apply_humanization.py <humanized_part1> <humanized_part2>"
    )


if __name__ == "__main__":
    build_pdfs()
